import { ComponentTemplate } from '../types/architecture';

export const COMPONENT_TEMPLATES: ComponentTemplate[] = [
  // Gateway & Load Balancers
  {
    id: 'api-gateway',
    label: 'API Gateway',
    category: 'gateway',
    tech: 'Kong / Envoy',
    defaultLatency: 8,
    defaultCapacity: 20000,
    defaultFailureRate: 0.1,
    defaultReplication: 'Active-Active Cluster',
    description: 'Routes traffic, handles authentication, rate limiting, and SSL termination.',
    iconName: 'Network',
  },
  {
    id: 'load-balancer',
    label: 'Cloud Load Balancer',
    category: 'gateway',
    tech: 'AWS ALB / NGINX',
    defaultLatency: 5,
    defaultCapacity: 35000,
    defaultFailureRate: 0.05,
    defaultReplication: 'Multi-AZ Anycast',
    description: 'Distributes incoming HTTP/TCP connections across downstream service pools.',
    iconName: 'Split',
  },
  {
    id: 'cdn',
    label: 'Edge CDN',
    category: 'gateway',
    tech: 'Cloudflare / CloudFront',
    defaultLatency: 15,
    defaultCapacity: 100000,
    defaultFailureRate: 0.01,
    defaultReplication: 'Global PoP Network',
    description: 'Caches static media and terminates TLS at the edge closest to end users.',
    iconName: 'Globe',
  },

  // Services & Compute
  {
    id: 'auth-service',
    label: 'Auth Service',
    category: 'service',
    tech: 'Node.js / OAuth2',
    defaultLatency: 25,
    defaultCapacity: 8000,
    defaultFailureRate: 0.2,
    defaultReplication: 'Auto-scaling (3-10 pods)',
    description: 'Issues JWTs, verifies identity tokens, and handles user session state.',
    iconName: 'ShieldCheck',
  },
  {
    id: 'order-service',
    label: 'Order Processing',
    category: 'service',
    tech: 'Go / gRPC',
    defaultLatency: 45,
    defaultCapacity: 5000,
    defaultFailureRate: 0.5,
    defaultReplication: 'Auto-scaling (5 pods)',
    description: 'Coordinates checkout, inventory reservations, and payment dispatch.',
    iconName: 'ShoppingCart',
  },
  {
    id: 'user-service',
    label: 'User Service',
    category: 'service',
    tech: 'FastAPI / Python',
    defaultLatency: 30,
    defaultCapacity: 6000,
    defaultFailureRate: 0.2,
    defaultReplication: 'Multi-container ECS',
    description: 'Manages user profile CRUD, preferences, and social graph connections.',
    iconName: 'Users',
  },
  {
    id: 'search-service',
    label: 'Search & Ranking',
    category: 'service',
    tech: 'Java / Elasticsearch',
    defaultLatency: 70,
    defaultCapacity: 4000,
    defaultFailureRate: 0.8,
    defaultReplication: 'Clustered 3x Replicas',
    description: 'Executes inverted-index fuzzy searches and vector similarity queries.',
    iconName: 'Search',
  },
  {
    id: 'notification-worker',
    label: 'Notification Worker',
    category: 'service',
    tech: 'Python Celery / BullMQ',
    defaultLatency: 60,
    defaultCapacity: 3000,
    defaultFailureRate: 1.0,
    defaultReplication: 'Worker Pool (10 threads)',
    description: 'Consumes queue jobs to dispatch emails, SMS, and push notifications.',
    iconName: 'Bell',
  },

  // Databases
  {
    id: 'postgres-db',
    label: 'Relational DB',
    category: 'database',
    tech: 'PostgreSQL 16',
    defaultLatency: 20,
    defaultCapacity: 3000,
    defaultFailureRate: 0.1,
    defaultReplication: 'Primary + 2 Read Replicas',
    description: 'ACID-compliant relational store with foreign keys and strict schemas.',
    iconName: 'Database',
  },
  {
    id: 'mongodb',
    label: 'Document Store',
    category: 'database',
    tech: 'MongoDB Atlas',
    defaultLatency: 18,
    defaultCapacity: 4500,
    defaultFailureRate: 0.2,
    defaultReplication: 'Replica Set (1P / 2S)',
    description: 'Flexible JSON schema storage for catalogs, telemetry, and fast ingestion.',
    iconName: 'FileSpreadsheet',
  },
  {
    id: 'cassandra',
    label: 'Wide-Column Store',
    category: 'database',
    tech: 'Apache Cassandra',
    defaultLatency: 15,
    defaultCapacity: 12000,
    defaultFailureRate: 0.2,
    defaultReplication: 'Peer-to-Peer Ring (RF=3)',
    description: 'Linearly scalable distributed write-optimized store for time-series & audit logs.',
    iconName: 'Layers',
  },

  // Caches
  {
    id: 'redis-cache',
    label: 'In-Memory Cache',
    category: 'cache',
    tech: 'Redis Cluster',
    defaultLatency: 2,
    defaultCapacity: 25000,
    defaultFailureRate: 0.05,
    defaultReplication: 'Primary-Replica with Sentinel',
    description: 'Sub-millisecond key-value caching layer, leaderboards, and session stores.',
    iconName: 'Zap',
  },
  {
    id: 'memcached',
    label: 'Distributed Cache',
    category: 'cache',
    tech: 'Memcached',
    defaultLatency: 1.5,
    defaultCapacity: 30000,
    defaultFailureRate: 0.05,
    defaultReplication: 'Consistent Hashing Ring',
    description: 'High-speed multithreaded volatile object cache for frequent read queries.',
    iconName: 'Flame',
  },

  // Message Queues & Streaming
  {
    id: 'kafka-cluster',
    label: 'Event Streaming',
    category: 'queue',
    tech: 'Apache Kafka',
    defaultLatency: 10,
    defaultCapacity: 40000,
    defaultFailureRate: 0.1,
    defaultReplication: '3 Brokers (ISR=2)',
    description: 'Durable distributed commit log for event-driven decoupled architectures.',
    iconName: 'Radio',
  },
  {
    id: 'rabbitmq',
    label: 'Message Broker',
    category: 'queue',
    tech: 'RabbitMQ',
    defaultLatency: 12,
    defaultCapacity: 15000,
    defaultFailureRate: 0.2,
    defaultReplication: 'Quorum Queues',
    description: 'AMQP broker with complex exchange routing, dead-lettering, and priority queues.',
    iconName: 'FastForward',
  },

  // Storage
  {
    id: 's3-bucket',
    label: 'Object Storage',
    category: 'storage',
    tech: 'Amazon S3 / MinIO',
    defaultLatency: 40,
    defaultCapacity: 10000,
    defaultFailureRate: 0.01,
    defaultReplication: '99.999999999% (11 9s) Durability',
    description: 'Scalable immutable blob store for videos, images, logs, and backups.',
    iconName: 'HardDrive',
  },

  // Clients
  {
    id: 'web-client',
    label: 'Web Browser Client',
    category: 'api',
    tech: 'Next.js / SPA',
    defaultLatency: 80,
    defaultCapacity: 50000,
    defaultFailureRate: 0.5,
    defaultReplication: 'Global Clients',
    description: 'End-user desktop browsers sending HTTPS requests and WebSocket events.',
    iconName: 'Laptop',
  },
  {
    id: 'mobile-app',
    label: 'Mobile Application',
    category: 'api',
    tech: 'React Native / iOS / Android',
    defaultLatency: 120,
    defaultCapacity: 50000,
    defaultFailureRate: 1.0,
    defaultReplication: 'Cellular / Wi-Fi',
    description: 'Native mobile client with intermittent connectivity and retry logic.',
    iconName: 'Smartphone',
  },
];
