import { PresetArchitecture } from '../types/architecture';

export const PRESET_ARCHITECTURES: PresetArchitecture[] = [
  {
    id: 'ecommerce-microservices',
    name: 'E-Commerce Microservices',
    description: 'Scalable transactional e-commerce engine with caching, message queue decoupling, and database replication.',
    mode: 'pro',
    nodes: [
      {
        id: 'node-client',
        type: 'architectureNode',
        position: { x: 50, y: 220 },
        data: {
          label: 'Client Apps',
          category: 'api',
          tech: 'Next.js & React Native',
          latency: 60,
          rps: 4500,
          capacity: 20000,
          failureRate: 0.1,
          replication: 'Global Endpoints',
          description: 'Web storefront and mobile shopper traffic.',
          explanation: 'Entry point for all customer browsing, searching, and purchasing actions.',
        },
      },
      {
        id: 'node-cdn',
        type: 'architectureNode',
        position: { x: 300, y: 100 },
        data: {
          label: 'Edge CDN',
          category: 'gateway',
          tech: 'Cloudflare Workers',
          latency: 12,
          rps: 3000,
          capacity: 40000,
          failureRate: 0.05,
          replication: 'Global Anycast Edge',
          description: 'Caches product images, static web bundles, and catalog thumbnails.',
          explanation: 'Offloads 70% of static asset bandwidth before touching core origin servers.',
        },
      },
      {
        id: 'node-gateway',
        type: 'architectureNode',
        position: { x: 300, y: 320 },
        data: {
          label: 'API Gateway',
          category: 'gateway',
          tech: 'Kong Gateway / Envoy',
          latency: 8,
          rps: 4500,
          capacity: 12000,
          failureRate: 0.1,
          replication: 'Active-Active Cluster',
          description: 'Handles rate limiting, JWT token validation, and path routing.',
          explanation: 'Single secure ingress point routing /orders, /users, and /products.',
        },
      },
      {
        id: 'node-order-service',
        type: 'architectureNode',
        position: { x: 580, y: 200 },
        data: {
          label: 'Order Service',
          category: 'service',
          tech: 'Go / gRPC',
          latency: 35,
          rps: 2200,
          capacity: 3500,
          failureRate: 0.3,
          replication: '4 Pods (HPA Enabled)',
          description: 'Processes checkout carts, validates inventory, and initiates payments.',
          explanation: 'Core business service requiring transactional consistency.',
        },
      },
      {
        id: 'node-user-service',
        type: 'architectureNode',
        position: { x: 580, y: 440 },
        data: {
          label: 'User & Catalog Service',
          category: 'service',
          tech: 'Node.js / Express',
          latency: 28,
          rps: 2300,
          capacity: 5000,
          failureRate: 0.2,
          replication: '3 Pods Auto-scaling',
          description: 'Serves product catalog metadata and user account profiles.',
          explanation: 'Read-heavy service heavily backed by redis caching.',
        },
      },
      {
        id: 'node-redis',
        type: 'architectureNode',
        position: { x: 860, y: 380 },
        data: {
          label: 'Redis Cluster',
          category: 'cache',
          tech: 'Redis 7.2 (Sentinel)',
          latency: 2,
          rps: 2100,
          capacity: 25000,
          failureRate: 0.05,
          replication: 'Primary-Replica Cluster',
          description: 'Hot product catalog caching and user session state storage.',
          explanation: 'Protects primary database from read spikes with sub-2ms lookups.',
        },
      },
      {
        id: 'node-kafka',
        type: 'architectureNode',
        position: { x: 860, y: 150 },
        data: {
          label: 'Kafka Event Bus',
          category: 'queue',
          tech: 'Apache Kafka',
          latency: 10,
          rps: 2200,
          capacity: 30000,
          failureRate: 0.05,
          replication: '3 Brokers (Replication Factor 3)',
          description: 'Durable event log for order.placed, payment.succeeded, inventory.reserved.',
          explanation: 'Asynchronously decouples order confirmation from notification and shipping workers.',
        },
      },
      {
        id: 'node-notif-worker',
        type: 'architectureNode',
        position: { x: 1140, y: 100 },
        data: {
          label: 'Notification Worker',
          category: 'service',
          tech: 'Python Celery',
          latency: 55,
          rps: 1200,
          capacity: 2500,
          failureRate: 0.5,
          replication: '6 Worker Threads',
          description: 'Consumes order events and sends confirmation emails & push alerts.',
          explanation: 'Worker that operates asynchronously so user response time is never delayed.',
        },
      },
      {
        id: 'node-postgres',
        type: 'architectureNode',
        position: { x: 1140, y: 320 },
        data: {
          label: 'Postgres Primary',
          category: 'database',
          tech: 'AWS Aurora PostgreSQL',
          latency: 22,
          rps: 1800,
          capacity: 3000,
          failureRate: 0.1,
          replication: 'Primary with 2 Aurora Read Replicas',
          description: 'ACID transactional data store for orders, payments, and account balances.',
          explanation: 'Reliable transactional truth for all financial and inventory state.',
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'node-client', target: 'node-cdn', label: 'Static Assets', animated: true, data: { protocol: 'HTTP/REST' } },
      { id: 'e2', source: 'node-client', target: 'node-gateway', label: 'API Requests', animated: true, data: { protocol: 'HTTP/REST' } },
      { id: 'e3', source: 'node-gateway', target: 'node-order-service', label: 'POST /checkout', animated: true, data: { protocol: 'gRPC' } },
      { id: 'e4', source: 'node-gateway', target: 'node-user-service', label: 'GET /catalog', animated: true, data: { protocol: 'gRPC' } },
      { id: 'e5', source: 'node-user-service', target: 'node-redis', label: 'Cache Lookup', animated: true, data: { protocol: 'TCP' } },
      { id: 'e6', source: 'node-user-service', target: 'node-postgres', label: 'DB Read Miss', animated: true, data: { protocol: 'SQL' } },
      { id: 'e7', source: 'node-order-service', target: 'node-postgres', label: 'Write Order', animated: true, data: { protocol: 'SQL' } },
      { id: 'e8', source: 'node-order-service', target: 'node-kafka', label: 'Publish Event', animated: true, data: { protocol: 'Kafka Topic' } },
      { id: 'e9', source: 'node-kafka', target: 'node-notif-worker', label: 'Consume Job', animated: true, data: { protocol: 'Kafka Topic' } },
    ],
  },
  {
    id: 'video-streaming',
    name: 'Global Video Streaming (YouTube/Netflix)',
    description: 'High-throughput video upload, asynchronous multi-bitrate transcoding pipeline, and global CDN delivery.',
    mode: 'pro',
    nodes: [
      {
        id: 'v-client',
        type: 'architectureNode',
        position: { x: 50, y: 220 },
        data: {
          label: 'Viewer & Creator Clients',
          category: 'api',
          tech: 'Smart TVs & Web Players',
          latency: 40,
          rps: 12000,
          capacity: 50000,
          failureRate: 0.2,
          replication: 'Global',
          description: 'HLS / DASH video streaming clients and video uploaders.',
          explanation: 'Requests video chunk manifests and sends raw video uploads.',
        },
      },
      {
        id: 'v-cdn',
        type: 'architectureNode',
        position: { x: 320, y: 100 },
        data: {
          label: 'Global CDN Network',
          category: 'gateway',
          tech: 'Fastly / Akamai Edge',
          latency: 10,
          rps: 10500,
          capacity: 60000,
          failureRate: 0.01,
          replication: '300+ Edge PoPs',
          description: 'Caches fragmented MP4 / HLS video segments at ISP edges.',
          explanation: 'Serves 95% of video bandwidth directly from edge cache.',
        },
      },
      {
        id: 'v-gateway',
        type: 'architectureNode',
        position: { x: 320, y: 340 },
        data: {
          label: 'Ingress Load Balancer',
          category: 'gateway',
          tech: 'NGINX Plus / AWS ALB',
          latency: 6,
          rps: 1500,
          capacity: 15000,
          failureRate: 0.05,
          replication: 'Multi-AZ',
          description: 'Routes API metadata queries and chunked video upload payloads.',
          explanation: 'Distributes traffic to transcoding pipeline and metadata services.',
        },
      },
      {
        id: 'v-api',
        type: 'architectureNode',
        position: { x: 600, y: 340 },
        data: {
          label: 'Video Metadata Service',
          category: 'service',
          tech: 'FastAPI / gRPC',
          latency: 24,
          rps: 1500,
          capacity: 6000,
          failureRate: 0.1,
          replication: 'Kubernetes Cluster',
          description: 'Handles comments, view counts, user subscriptions, and video metadata.',
          explanation: 'Fast lightweight microservice answering catalog queries.',
        },
      },
      {
        id: 'v-queue',
        type: 'architectureNode',
        position: { x: 600, y: 160 },
        data: {
          label: 'Transcode Queue',
          category: 'queue',
          tech: 'RabbitMQ / AWS SQS',
          latency: 8,
          rps: 400,
          capacity: 10000,
          failureRate: 0.05,
          replication: 'Quorum Queues',
          description: 'Queues newly uploaded raw video files for multi-resolution encoding.',
          explanation: 'Prevents video uploads from exhausting CPU transcoding servers.',
        },
      },
      {
        id: 'v-transcoder',
        type: 'architectureNode',
        position: { x: 880, y: 160 },
        data: {
          label: 'Transcoding Cluster',
          category: 'service',
          tech: 'FFmpeg GPU Workers',
          latency: 450,
          rps: 400,
          capacity: 800,
          failureRate: 1.2,
          replication: 'Spot GPU Instances',
          description: 'Splits raw 4K videos into 1080p, 720p, 480p HLS chunks.',
          explanation: 'Heavy compute cluster transcoding videos in parallel.',
        },
      },
      {
        id: 'v-s3',
        type: 'architectureNode',
        position: { x: 1140, y: 220 },
        data: {
          label: 'Object Storage (S3)',
          category: 'storage',
          tech: 'Amazon S3 Standard',
          latency: 35,
          rps: 1200,
          capacity: 15000,
          failureRate: 0.01,
          replication: '11 9s Durability across 3 AZs',
          description: 'Stores master video files and encoded HLS segment blobs.',
          explanation: 'Origin storage providing files to CDN on cache miss.',
        },
      },
      {
        id: 'v-db',
        type: 'architectureNode',
        position: { x: 880, y: 380 },
        data: {
          label: 'NoSQL Metadata DB',
          category: 'database',
          tech: 'ScyllaDB / Cassandra',
          latency: 14,
          rps: 1500,
          capacity: 10000,
          failureRate: 0.1,
          replication: 'Peer-to-Peer Cluster',
          description: 'Stores high-frequency video playback telemetry and metadata.',
          explanation: 'Wide-column distributed database with zero single-point of failure.',
        },
      },
    ],
    edges: [
      { id: 've1', source: 'v-client', target: 'v-cdn', label: 'Fetch Chunks', animated: true, data: { protocol: 'HTTP/REST' } },
      { id: 've2', source: 'v-client', target: 'v-gateway', label: 'Upload / Query', animated: true, data: { protocol: 'HTTP/REST' } },
      { id: 've3', source: 'v-cdn', target: 'v-s3', label: 'Cache Miss Origin', animated: true, data: { protocol: 'HTTP/REST' } },
      { id: 've4', source: 'v-gateway', target: 'v-queue', label: 'Queue Upload', animated: true, data: { protocol: 'gRPC' } },
      { id: 've5', source: 'v-gateway', target: 'v-api', label: 'Metadata API', animated: true, data: { protocol: 'gRPC' } },
      { id: 've6', source: 'v-queue', target: 'v-transcoder', label: 'Encode Job', animated: true, data: { protocol: 'TCP' } },
      { id: 've7', source: 'v-transcoder', target: 'v-s3', label: 'Save HLS Segments', animated: true, data: { protocol: 'HTTP/REST' } },
      { id: 've8', source: 'v-api', target: 'v-db', label: 'Query Video Info', animated: true, data: { protocol: 'TCP' } },
    ],
  },
  {
    id: 'learner-url-shortener',
    name: 'URL Shortener (TinyURL) - Learner Guide',
    description: 'Clear educational architecture showing how high-read systems scale using reverse proxy, cache, and database.',
    mode: 'learner',
    nodes: [
      {
        id: 'u-user',
        type: 'architectureNode',
        position: { x: 50, y: 220 },
        data: {
          label: 'Web Browser / Mobile',
          category: 'api',
          tech: 'Client Browser',
          latency: 50,
          rps: 2000,
          capacity: 10000,
          failureRate: 0.1,
          replication: 'End Users',
          description: 'Clicks shortened links like https://bit.ly/3xYz or generates new links.',
          explanation: 'What: The user interface where visitors click links or paste long URLs to be shortened.',
        },
      },
      {
        id: 'u-lb',
        type: 'architectureNode',
        position: { x: 300, y: 220 },
        data: {
          label: 'Load Balancer',
          category: 'gateway',
          tech: 'NGINX Reverse Proxy',
          latency: 5,
          rps: 2000,
          capacity: 8000,
          failureRate: 0.05,
          replication: 'Redundant Pair',
          description: 'Distributes incoming traffic smoothly between multiple application web servers.',
          explanation: 'Why: If one web server crashes, the load balancer automatically sends traffic to surviving servers without downtime.',
        },
      },
      {
        id: 'u-app',
        type: 'architectureNode',
        position: { x: 560, y: 220 },
        data: {
          label: 'URL Shortener App',
          category: 'service',
          tech: 'Node.js / FastAPI Service',
          latency: 20,
          rps: 2000,
          capacity: 4000,
          failureRate: 0.2,
          replication: 'Stateless App Cluster',
          description: 'Encodes long URLs using Base62 algorithms and returns 301/302 HTTP redirects.',
          explanation: 'What: Contains the hashing algorithm (Base62) that turns 100-character URLs into 7-character aliases.',
        },
      },
      {
        id: 'u-cache',
        type: 'architectureNode',
        position: { x: 840, y: 120 },
        data: {
          label: 'Redis Cache',
          category: 'cache',
          tech: 'Redis (In-Memory)',
          latency: 2,
          rps: 1700,
          capacity: 15000,
          failureRate: 0.05,
          replication: 'Leader-Follower Cache',
          description: 'Stores frequently clicked short URL -> long URL mappings in high-speed RAM.',
          explanation: 'Why: Reading from RAM takes 2ms, whereas reading from disk takes 25ms. The 80/20 rule says 20% of links generate 80% of traffic!',
        },
      },
      {
        id: 'u-db',
        type: 'architectureNode',
        position: { x: 840, y: 320 },
        data: {
          label: 'Persistent Database',
          category: 'database',
          tech: 'PostgreSQL Database',
          latency: 22,
          rps: 300,
          capacity: 2500,
          failureRate: 0.1,
          replication: 'Primary + 2 Read Replicas',
          description: 'Durable disk storage holding billions of shortened URL mapping records.',
          explanation: 'Why: RAM is volatile and expensive. The database guarantees URLs are permanently saved even if power is lost.',
        },
      },
    ],
    edges: [
      { id: 'ue1', source: 'u-user', target: 'u-lb', label: 'HTTP Request', animated: true, data: { protocol: 'HTTP/REST' } },
      { id: 'ue2', source: 'u-lb', target: 'u-app', label: 'Forward Request', animated: true, data: { protocol: 'HTTP/REST' } },
      { id: 'ue3', source: 'u-app', target: 'u-cache', label: '1. Check Cache (Hit)', animated: true, data: { protocol: 'TCP' } },
      { id: 'ue4', source: 'u-app', target: 'u-db', label: '2. Fallback DB (Miss/Write)', animated: true, data: { protocol: 'SQL' } },
    ],
  },
];
